# Conexión a MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/restaurante
spring.data.mongodb.database=restaurante

# Nombre de la app
spring.application.name=restaurante

# Puerto del servidor (opcional, 8080 es el default)
server.port=8080

# Jwt
jwt.secret=esta-clave-debe-tener-al-menos-32-caracteres-para-ser-segura
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
